### PR TITLE
Create fr.js

### PR DESCRIPTION
**Pull request by SGe-GH**
French translation;
Search for 3 comments starting with "// -- SGe-GH ::"

### CODE REVIEW

**Comment by czyzby** [comment]
Thanks! Don't worry about the failed checks, it's just file formatting. I'll take care of this.

**Comment by czyzby** [comment]
@SGe-GH I've fixed the file and also changed how some messages are shown to account for the French punctuation.

The "of" text is shown in table pagination in the card loading screen. As in "1 of 5". Google Translate translated that to "sur", as in "1 sur 5", so I added that to the file. Let me know if that's correct.

Anyway, the translation should be available on the official website. Please test it if you have some time. Thanks again for the contribution!

**Comment by SGe-GH** [comment]
> @SGe-GH I've fixed the file and also changed how some messages are shown to account for the French punctuation.
> 
> The "of" text is shown in table pagination in the card loading screen. As in "1 of 5". Google Translate translated that to "sur", as in "1 sur 5", so I added that to the file. Let me know if that's correct.
> 
> Anyway, the translation should be available on the official website. Please test it if you have some time. Thanks again for the contribution!

Hello, checked online: the french punctuation is OK; the "of" = "sur" in this case is right translation.

The only thing not right: I translated the keywords like "Injury" but they are not handled to be changed in the spell/power description. So I should change them back to their english version so users don't think there's a bug with keywords.

**Comment by czyzby** [comment]
Right, I'll correct this.

**Comment by czyzby** [comment]
@SGe-GH The reason why the keywords are all in English is because I wanted the icons to work even when changing the locale or import a card made by someone else. If you think I should reconsider this, I might make the keywords translatable.

**Comment by SGe-GH** [comment]
I'm not sure it's worth the effort to translate keywords in the code, more so if  it might side effects on the current profile when  the locales. It's just I rushed headlong when I translated and forgot to adapt this sentence.

**Comment by czyzby** [comment]
@SGe-GH The side effect would be that any time you change the locale, some icons would be changed to text. Not saying that's necessarily a bad thing. It would be relatively easy for me to change the keywords in code, if that's what you're worried about - I'm more concerned about the user experience. You'd probably expect the entire application - including the keywords - to be translated when you switch the locale. I'd have to think about it.

**Comment by SGe-GH** [comment]
I think it can stay like this for and can be changed at a later time if users find this confusing. But there are so few keywords and most are obvious that it won't be really bothering for the users (at the very least, trying the keywords one doesn't understand is easy enough with an immediate result ^^).

**Comment by czyzby** [comment]
Yeah, but having to try out the keywords is still a workaround. If I find a quick way to do this, I'll translate the keywords and see how it works. Thanks for pointing that out.

**Pull request merged**
